"""Your migration message

Revision ID: 3d21edff714f
Revises: d12b62c8f612
Create Date: 2025-01-08 17:08:30.474365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d21edff714f'
down_revision: Union[str, None] = 'd12b62c8f612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', sa.String(length=73), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('video_duration', sa.Integer(), nullable=True),
    sa.Column('video_frame_rate', sa.Integer(), nullable=True),
    sa.CheckConstraint('media_type IN (0, 1)', name='check_valid_media_type'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medias')
    # ### end Alembic commands ###
